# Generated by Django 3.1.5 on 2021-02-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_active', models.BooleanField(default=False)),
                ('bedtype', models.CharField(choices=[('1', 'single'), ('2', 'double'), ('3', 'triple')], max_length=30)),
                ('room_no', models.IntegerField(blank=True, null=True)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype')),
            ],
        ),
    ]
