# Generated by Django 3.1.5 on 2021-02-01 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210201_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
