# Generated by Django 3.1.5 on 2021-02-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210201_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
